branch-defaults:
  main:
    environment: Unimex-prd
environment-defaults:
  Unimex-prd:
    branch: main
    repository: origin
global:
  application_name: unimex
  default_ec2_keyname: unimex
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
