"""
Django settings for unimex project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
from dotenv import load_dotenv
from django.contrib.messages import constants as messages
load_dotenv()
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == 'True'

ALLOWED_HOSTS = [
    'localhost', 
    'unimex.click',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'django_extensions',
    'django_extensions',
    'crispy_forms',
    'crispy_bootstrap5',
    'dal',
    'dal_select2',
    'django_select2',
    'storages',
    "bootstrap_datepicker_plus",
    #'apps',
    'accounts',
    'clients',
    'tasks',
    'reports',
    'companies',
    'balance',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = 'bootstrap5'

MIDDLEWARE = [
    'unimex.middleware.HealthCheckMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'unimex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'unimex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
'''
DATABASES = {
       'default': {
           'ENGINE': 'django.db.backends.postgresql',
           'NAME': 'unimex',
            'USER': 'unimexuser',
            'PASSWORD': 'changeme',
            'HOST': '192.168.56.101',
            'PORT': '5432',
        }
    }
'''

if os.environ.get('DEBUG') == 'True':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': '/home/wquitian/Documents/projects/db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': '/home/webapp/db.sqlite3',
        }
    }

'''   
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.oracle',
            'NAME': 'unimex_high',  
            'USER': 'admin',
            'PASSWORD': 'William13***',
            'OPTIONS': {
                'wallet_location': '/u01/app/oracle/product/client23/network/admin',
                "wallet_password": "William13***",
            }
        }
    }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': '/home/william/db.sqlite3',
    },
    'copymysql': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'unimex',
        'USER': 'admin',
        'PASSWORD': 'William13*',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}
'''
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGES = (('es', 'Spanish'), ('en', 'English'))

#DATE_INPUT_FORMATS = ['%m/%d/%Y']
DATE_FORMAT = 'm/d/Y'
DATETIME_FORMAT = 'm/d/Y h:i:s A'

LANGUAGE_CODE = 'es'

# Negocio en Tennessee (hora Central). Sin esta línea Django cae al default global
# 'America/Chicago', pero la plantilla de startproject escribe 'UTC': dejarlo implícito
# corre las fronteras de día del balance 5-6 horas si alguien regenera settings.
TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_TZ = True

# Set session to expire after 15 minutes (900 seconds) of inactivity
SESSION_COOKIE_AGE = 1800  # seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
#STATIC_ROOT = os.path.join(BASE_DIR, "static")
#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static_files')]
#STATICFILES_DIRS = [BASE_DIR / 'static']

if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

default_storage_backend = "storages.backends.s3.S3Storage"
default_storage_options = {
    "access_key": os.environ.get('S3_ACCESS_KEY'),
    "secret_key": os.environ.get('S3_SECRET_KEY'),
    "bucket_name": os.environ.get('S3_BUCKET_NAME'),
    "region_name": os.environ.get('S3_REGION_NAME'),
}

STORAGES = {
    "default": {
        "BACKEND": default_storage_backend,
        "OPTIONS": {
                **default_storage_options,
                "location": "media",
            },
        },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    },
}

BOOTSTRAP_DATEPICKER_PLUS = {
    "options": {
        "locale": "es-us",
    },
    "variant_options": {
        "date": {
            "format": "MM/DD/YYYY",
        },
    }
}

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}
