# Generated by Django 5.2.1 on 2025-05-17 18:10

import clients.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerMoneyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_moneyorder_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.country')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.FileField(upload_to=clients.models.Document.upload_rename, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg']), clients.models.Document.validate_file_size])),
                ('document_type', models.CharField(choices=[('AT', 'Autorización de trabajo'), ('CC', 'Cédula de Ciudadanía '), ('CE', 'Credencial Electoral'), ('DNI', 'DNI'), ('DPI', 'DPI'), ('F1025', 'F1025'), ('IE', 'Identificación estatal'), ('LC', 'Licencia de Conducir'), ('MC', 'Matrícula Consular'), ('PA', 'Pasaporte'), ('PI', 'Prueba de Ingresos'), ('RN', 'Registro Nacional'), ('RE', 'Residencia')], max_length=5)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='FidelityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(999999.9)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('broker_moneyorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.brokermoneyorder')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyorder', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='SendMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(999999.9)])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.broker')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendmoney', to='clients.client')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.country')),
                ('fidelitycard', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sendmoney', to='clients.fidelitycard')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='cards',
            field=models.ManyToManyField(through='clients.SendMoney', to='clients.fidelitycard'),
        ),
        migrations.CreateModel(
            name='SendPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_length', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(9999.9)])),
                ('size_width', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(9999.9)])),
                ('size_heigth', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(9999.9)])),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(9999.9)])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendpackage', to='clients.client')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.country')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.shipper')),
            ],
        ),
    ]
