# Generated by Django 5.2.1 on 2025-06-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_company_profession_client_company_client_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sendmoney',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
