# Generated by Django 5.2.1 on 2025-07-27 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_company_name_alter_profession_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('AT', 'Autorización de trabajo'), ('CC', 'Cédula de Ciudadanía '), ('CE', 'Credencial Electoral'), ('DNI', 'DNI'), ('DUI', 'Documento Único de Identificación'), ('DPI', 'DPI'), ('F1025', 'F1025'), ('FA', 'Foto Actual'), ('IE', 'Identificación estatal'), ('LC', 'Licencia de Conducir'), ('MC', 'Matrícula Consular'), ('PA', 'Pasaporte'), ('PI', 'Prueba de Ingresos'), ('RN', 'Registro Nacional'), ('RE', 'Residencia'), ('RENAP', 'RENAP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sendmoney',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
