# Generated by Django 5.2.1 on 2025-08-02 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmoney',
            name='broker_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
