# Generated by Django 5.2.1 on 2025-08-23 16:33

import clients.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_sendmoney_broker_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.FileField(upload_to=clients.models.Document.upload_rename, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg']), clients.models.Document.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='sendmoney',
            name='broker_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('check_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)])),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.company')),
                ('manage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.manager')),
            ],
        ),
    ]
