# Generated by Django 5.2.1 on 2025-08-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_manager_alter_document_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='manage',
            new_name='manager',
        ),
    ]
