# Generated by Django 5.2.1 on 2025-08-28 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_check_author_check_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
