# Generated by Django 5.2.1 on 2025-08-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_check_created_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manager',
            constraint=models.UniqueConstraint(fields=('name', 'phone'), name='unique_name_phone'),
        ),
    ]
