# Generated by Django 5.2.1 on 2025-08-28 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_manager_unique_name_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.manager'),
            preserve_default=False,
        ),
    ]
