# Generated by Django 5.2.1 on 2025-08-28 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_check_company_alter_check_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='clients.company'),
        ),
        migrations.AlterField(
            model_name='check',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='clients.manager'),
        ),
    ]
