# Generated by Django 5.2.1 on 2025-08-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_check_company_alter_check_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
