# Generated by Django 5.2.1 on 2025-08-28 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_alter_manager_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator(message='Número de télefono debe tener 10 dígitos.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
