# Generated by Django 5.2.1 on 2025-08-28 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_alter_manager_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='clients.client'),
            preserve_default=False,
        ),
    ]
