# Generated by Django 5.2.1 on 2025-08-30 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_check_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='clients.manager'),
        ),
    ]
