# Generated by Django 5.2.1 on 2025-08-30 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_alter_check_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Número de télefono debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
    ]
