# Generated by Django 5.2.1 on 2025-08-31 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_alter_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='manager',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='clients.manager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
