# Generated by Django 5.2.1 on 2025-08-31 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_check_manager_alter_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='clients.manager'),
        ),
    ]
