# Generated by Django 5.2.1 on 2025-09-01 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_alter_check_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moneyorder',
            name='broker_moneyorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_mo', to='clients.brokermoneyorder'),
        ),
    ]
