# Generated by Django 5.2.1 on 2025-09-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_alter_manager_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyorder',
            name='broker_moneyorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.brokermoneyorder'),
        ),
    ]
