# Generated by Django 5.2.11 on 2026-02-27 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_alter_moneyorder_broker_moneyorder'),
        ('companies', '0007_alter_company_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='companies.manager'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
