# Generated by Django 5.2.11 on 2026-02-27 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_alter_check_manager_delete_manager'),
        ('companies', '0007_alter_company_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='check',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
