# Generated by Django 5.2.11 on 2026-04-17 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_alter_client_company_alter_check_company_and_more'),
        ('companies', '0016_remove_company_ein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='check',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='companies.manager'),
        ),
    ]
