# Generated by Django 5.2.11 on 2026-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_alter_check_company_alter_check_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
