# Generated by Django 5.2.11 on 2026-04-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_check_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmoney',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('vialink', 'ViaLink')], default='cash', max_length=10),
            preserve_default=False,
        ),
    ]
