# Generated by Django 5.2.11 on 2026-04-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_sendmoney_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmoney',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('vialink', 'ViaLink')], default='cash', max_length=10),
        ),
    ]
