# Generated by Django 5.2.11 on 2026-05-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_alter_sendmoney_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='comm_percent',
            field=models.DecimalField(choices=[('1.5', '1.5%'), ('1', '1%'), ('0', '0%')], decimal_places=1, default='1.5', max_digits=2),
        ),
    ]
