# Generated by Django 5.2.11 on 2026-05-01 01:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_check_comm_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='comm_percent',
            field=models.DecimalField(choices=[(Decimal('1.5'), '1.5%'), (Decimal('1.0'), '1%'), (Decimal('0.0'), '0%')], decimal_places=1, default=Decimal('1.5'), max_digits=3),
        ),
    ]
