# Generated by Django 5.2.11 on 2026-07-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_returnedcheck_returnedcheckcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedcheck',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
