# Generated by Django 5.2.11 on 2026-07-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_returnedcheck_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedcheck',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
