# Generated by Django 5.2.11 on 2026-07-28 21:28

import clients.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_alter_returnedcheck_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedcheck',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='returnedcheck',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=clients.models.ReturnedCheck.upload_rename, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg']), clients.models.ReturnedCheck.validate_file_size]),
        ),
    ]
