# Generated by Django 5.2.11 on 2026-07-30 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_returnedcheck_file_name_returnedcheck_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedcheck',
            name='reversal_check',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_check', to='clients.check'),
        ),
        migrations.AlterField(
            model_name='returnedcheck',
            name='original_check',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='returned_check', to='clients.check'),
        ),
    ]
