# Generated by Django 5.2.11 on 2026-07-30 01:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0039_returnedcheck_reversal_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='comm_percent',
            field=models.DecimalField(choices=[(Decimal('2.0'), '2%'), (Decimal('1.5'), '1.5%'), (Decimal('1.0'), '1%'), (Decimal('0.0'), '0%'), (Decimal('0.5'), '0.5%')], decimal_places=1, default=Decimal('1.5'), max_digits=3),
        ),
    ]
