# Generated by Django 5.2.11 on 2026-09-04 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_alter_check_comm_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moneyorder',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sendmoney',
            name='creation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
