# Generated by Django 5.2.11 on 2026-09-05 05:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0041_alter_check_created_at_alter_moneyorder_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedcheck',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('redepositado', 'Re-depositado'), ('recuperado', 'Recuperado'), ('perdido', 'Pérdida')], db_index=True, default='pendiente', max_length=15, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ReturnedCheckEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('returned', 'Devuelto'), ('redeposited', 'Re-depositado'), ('cleared', 'Re-depósito exitoso'), ('bounced', 'Rebotó de nuevo'), ('paid_cash', 'Cliente pagó en efectivo'), ('written_off', 'Dado por perdido')], max_length=15, verbose_name='Evento')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Fee cobrado')),
                ('comment', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('returned_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.returnedcheck')),
            ],
            options={
                'verbose_name': 'Evento de cheque devuelto',
                'verbose_name_plural': 'Eventos de cheques devueltos',
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
