# Generated by Django 5.2.11 on 2026-09-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_seed_returned_check_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedcheckevent',
            name='event_type',
            field=models.CharField(choices=[('returned', 'Devuelto'), ('redeposited', 'Re-depositado'), ('cleared', 'Re-depósito exitoso'), ('bounced', 'Rebotó de nuevo'), ('paid_cash', 'Cliente pagó en efectivo'), ('written_off', 'Dado por perdido'), ('comment', 'Comentario')], max_length=15, verbose_name='Evento'),
        ),
    ]
