# Generated by Django 5.2.11 on 2026-09-07 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_alter_returnedcheckevent_event_type'),
        ('companies', '0017_city_unique_city_name_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='check',
            constraint=models.UniqueConstraint(fields=('client', 'amount', 'check_number'), name='unique_check_client_amount_number', violation_error_message='Este cliente ya tiene un cheque con ese número y ese valor.'),
        ),
    ]
