# Generated by Django 5.2.11 on 2026-09-08 22:08

import clients.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_check_unique_check_client_amount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedcheck',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=clients.models.ReturnedCheck.upload_rename, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), clients.models.ReturnedCheck.validate_file_size]),
        ),
    ]
