# Generated by Django 5.2.11 on 2026-09-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_merge_returned_check_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedcheckevent',
            name='event_type',
            field=models.CharField(choices=[('returned', 'Devuelto'), ('redeposited', 'Re-depositado'), ('cleared', 'Re-depósito exitoso'), ('bounced', 'Rebotó de nuevo'), ('paid_cash', 'Cliente pagó en efectivo'), ('paid_check', 'Cliente pagó con cheque'), ('written_off', 'Dado por perdido'), ('comment', 'Comentario')], max_length=15, verbose_name='Evento'),
        ),
    ]
