# Generated by Django 5.2.11 on 2026-09-04 13:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0040_alter_check_comm_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_accounts', to='clients.broker', verbose_name='Broker de envíos')),
                ('broker_moneyorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_accounts', to='clients.brokermoneyorder', verbose_name='Broker de cheques / money orders')),
            ],
            options={
                'verbose_name': 'Cuenta de balance',
                'verbose_name_plural': 'Cuentas de balance',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('transfer', 'Traslado entre usuarios'), ('safebox', 'Depósito a caja fuerte'), ('bank', 'Depósito bancario'), ('expense', 'Gasto / retiro de caja')], max_length=20, verbose_name='Tipo de movimiento')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='balance.balanceaccount', verbose_name='Cuenta')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_created', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to=settings.AUTH_USER_MODEL, verbose_name='Entrega')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to=settings.AUTH_USER_MODEL, verbose_name='Recibe')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Balance inicial')),
                ('company_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Balance final empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_balances', to='balance.balanceaccount', verbose_name='Cuenta')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_balances_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_balances', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Balance diario',
                'verbose_name_plural': 'Balances diarios',
                'ordering': ['-date', 'account__order'],
                'constraints': [models.UniqueConstraint(fields=('user', 'account', 'date'), name='unique_daily_balance')],
            },
        ),
    ]
