# Generated by Django 5.2.11 on 2026-09-04 17:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_seed_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybalance',
            name='manual_movement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Movimiento del día'),
        ),
    ]
