# Generated by Django 5.2.11 on 2026-09-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_dailybalance_manual_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancemovement',
            name='movement_type',
            field=models.CharField(choices=[('transfer', 'Traslado entre usuarios'), ('safebox', 'Depósito a caja fuerte'), ('bank', 'Depósito bancario'), ('expense', 'Gasto / retiro de caja'), ('check_fee', 'Cobro fee cheque devuelto')], max_length=20, verbose_name='Tipo de movimiento'),
        ),
    ]
