# Generated by Django 5.2.1 on 2025-05-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('MO', 'Money Order'), ('SM', 'Envío de dinero'), ('SP', 'Envío de paquetes')], max_length=20),
        ),
    ]
