# Generated by Django 5.2.1 on 2025-09-09 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_alter_moneyorder_broker_moneyorder'),
        ('tasks', '0002_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('CHK', 'Cheque'), ('SM', 'Envío de dinero'), ('SP', 'Envío de paquetes'), ('MO', 'Money Order')], max_length=5),
        ),
    ]
