# Generated by Django 5.2.1 on 2025-09-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskfile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
