# Generated by Django 5.2.1 on 2025-09-21 19:41

import django.core.validators
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(upload_to=tasks.models.TaskFile.upload_rename, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg']), tasks.models.TaskFile.validate_file_size]),
        ),
    ]
