# Generated by Django 5.2.1 on 2025-09-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_taskfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('CHK', 'Cheque'), ('SM', 'Envío de dinero'), ('SP', 'Envío de paquetes'), ('MO', 'Money Order'), ('NA', 'Otros')], max_length=5),
        ),
    ]
