# Generated by Django 5.2.11 on 2026-02-26 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.city'),
        ),
        migrations.AddField(
            model_name='company',
            name='color',
            field=models.CharField(default='green', max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
