# Generated by Django 5.2.11 on 2026-02-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='short_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
