# Generated by Django 5.2.11 on 2026-02-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_state_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='color',
            field=models.CharField(default='green', max_length=15, null=True),
        ),
    ]
