# Generated by Django 5.2.11 on 2026-02-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
