# Generated by Django 5.2.11 on 2026-03-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ein',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
