# Generated by Django 5.2.11 on 2026-03-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_ein'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manager',
            constraint=models.UniqueConstraint(fields=('name', 'phone'), name='unique_name_phone'),
        ),
    ]
