# Generated by Django 5.2.11 on 2026-03-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=15, null=True),
        ),
    ]
