# Generated by Django 5.2.11 on 2026-03-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ein',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
