# Generated by Django 5.2.11 on 2026-04-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_company_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
