# Generated by Django 5.2.11 on 2026-04-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_remove_company_phone_company_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ein',
        ),
    ]
