# Generated by Django 5.2.11 on 2026-04-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_remove_company_ein'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'state'), name='unique_city_name_state'),
        ),
    ]
